#!/usr/bin/env python3
"""

Example usage:

./reload_policy_and_identity -p ../topology-json/topo-cisco/topo-cisco-policy.json -i ../topology-json/topo-cisco/topo-cisco-info.json
"""
import subprocess
import os
import argparse
from pathlib import Path


def cmd(txt, **kwargs):
    subprocess.run(txt, shell=True, check=True, **kwargs)

parser = argparse.ArgumentParser(description="Replace identity and policy files")

parser.add_argument(
    "-p",
    "--policy",
    type=str,
    required=True,
    help="the path to the policy file to replace the current one in place",
)
parser.add_argument(
    "-i",
    "--identity",
    type=str,
    required=False,
    help="the path to a identity mapping file to be run with the topoloy, ARGUMENT REQUIRED if running app 'netviews'",
)
parser.add_argument(
    "-r",
    "--prohibition",
    type=str,
    required=False,
    help="the path to a prohibition file to be run with the topoloy, ARGUMENT REQUIRED if running app 'netviews'",
)

args = parser.parse_args()

#print("=== Copying scenario files to local ONOS ===")
#cmd('cp -- scenarios/*.xml "$ONOS_ROOT/tools/test/scenarios/"')

experiment_env = {
    **os.environ,
    "NETVIEWS_POLICY": args.policy,
    "NETVIEWS_IDENTITY_MAPPING": args.identity,
    "NETVIEWS_PROHIBITION": args.prohibition
}

print("=== Replacing Policy and Identity Files ===")
cmd("stc reload_policy_and_identity", env=experiment_env)

print("=== All done! ===")
